# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: Invisionware.Net
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: buildTarget
    value: 'Nuget-Package'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget Tools'

- task: NuGetCommand@2
  displayName: 'Restore nuget packages'
  inputs:
    restoreSolution: '$(solution)'

- task: FileTransform@2
  displayName: 'Transform appsettings.json'
  inputs:
    folderPath: '$(Build.SourcesDirectory)\tests\**'
    jsonTargetFiles: |
      $(Build.SourcesDirectory)\tests\**\appsettings.json
      $(Build.SourcesDirectory)\tests\**\appsettings.$(buildConfiguration).json

- task: Cake@0
  displayName: 'Build Solution: Cake'
  inputs:
    script: 'build.cake'
    target: '$(buildTarget)'
    verbosity: 'Verbose'
    arguments: '-NugetArtifactsPath=$(Build.ArtifactStagingDirectory) -configuration=$(buildConfiguration)' 

- task: PublishTestResults@2
  displayName: 'Unit Tests: Publish results'
  enabled: true
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'tests/**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  enabled: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'