// ***********************************************************************
// Assembly         : Invisionware.Net.GeoCoding.Interfaces
// Author           : shawn.anderson
// Created          : 06-27-2015
//
// Last Modified By : shawn.anderson
// Last Modified On : 06-28-2015
// ***********************************************************************
// <copyright file="AddressTypes.cs" company="Invisionware">
//     Copyright ©  2015
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;

namespace Invisionware.Net.GeoCoding
{
	/// <summary>
	/// Enum AddressTypes
	/// </summary>
	public enum AddressTypes 
	{
		StreetAddress				, // = 0,
		Route						, // = 1 << 0,
		Intersection				, // = 1 << 1,
		Political					, // = 1 << 2,
		Country						, // = 1 << 3,
		AdministrativeAreaLevel1	, // = 1 << 4,
		AdministrativeAreaLevel2	, // = 1 << 5,
		AdministrativeAreaLevel3	, // = 1 << 6,
		AdministrativeAreaLevel4	, // = 1 << 7,
		AdministrativeAreaLevel5	, // = 1 << 8,
		ColloquialArea				, // = 1 << 9,
		Locality					, // = 1 << 10,
		Ward						, // = 1 << 11,
		Sublocality					, // = 1 << 12,
		Neighborhood				, // = 1 << 13,
		Premise						, // = 1 << 14,
		Subpremise					, // = 1 << 15,
		PostalCode					, // = 1 << 16,
		NaturalFeature				, // = 1 << 18,
		Airport						, // = 1 << 19,
		Park						, // = 1 << 20,
		PointOfInterest				, // = 1 << 21,
		Floor						, // = 1 << 22,
		Establishment				, // = 1 << 23,
		Parking						, // = 1 << 24,
		PostBox						, // = 1 << 25,
		PostalTown					, // = 1 << 26,
		Room						, // = 1 << 27,
		StreetNumber				, // = 1 << 28,
		BusStation					, // = 1 << 29,
		TrainStation				, // = 1 << 30,
		TransitStation				, // = 1 << 32,
		Geocode						, // = 1 << 33,
		PostalCodePrefix			, // = 1 << 34,
		PostalCodeSuffix			, // = 1 << 35,
		SublocalityLevel5			, // = 1 << 36,
		SublocalityLevel4			, // = 1 << 37,
		SublocalityLevel3			, // = 1 << 38,
		SublocalityLevel2			, // = 1 << 39,
		SublocalityLevel1			, // = 1 << 40,
		Accounting					, // = 1 << 41,
		AmusementPark				, // = 1 << 42,
		Aquarium					, // = 1 << 43,
		ArtGallery					, // = 1 << 44,
		Atm							, // = 1 << 45,
		Bakery						, // = 1 << 46,
		Bank						, // = 1 << 47,
		Bar							, // = 1 << 48,
		BeautySalon					, // = 1 << 49,
		BicycleStore				, // = 1 << 50,
		BookStore					, // = 1 << 51,
		BowlingAlley				, // = 1 << 52,
		Cafe						, // = 1 << 53,
		Campground					, // = 1 << 54,
		CarDealer					, // = 1 << 55,
		CarRental					, // = 1 << 56,
		CarRepair					, // = 1 << 57,
		CarWash						, // = 1 << 58,
		Casino						, // = 1 << 59,
		Cemetery					, // = 1 << 60,
		Church						, // = 1 << 61,
		CityHall					, // = 1 << 62,
		ClothingStore				, // = 1 << 64,
		ConvenienceStore			, // = 1 << 65,
		Courthouse					, // = 1 << 66,
		Dentist						, // = 1 << 67,
		DepartmentStore				, // = 1 << 68,
		Doctor						, // = 1 << 69,
		Electrician					, // = 1 << 70,
		ElectronicsStore			, // = 1 << 71,
		Embassy						, // = 1 << 72,
		Finance						, // = 1 << 73,
		FireStation					, // = 1 << 74,
		Florist						, // = 1 << 75,
		Food						, // = 1 << 76,
		FuneralHome					, // = 1 << 77,
		FurnitureStore				, // = 1 << 78,
		GasStation					, // = 1 << 79,
		GeneralContractor			, // = 1 << 80,
		GroceryOrSupermarket		, // = 1 << 81,
		Gym							, // = 1 << 82,
		HairCare					, // = 1 << 83,
		HardwareStore				, // = 1 << 84,
		Health						, // = 1 << 85,
		HinduTemple					, // = 1 << 86,
		HomeGoodsStore				, // = 1 << 87,
		Hospital					, // = 1 << 88,
		InsuranceAgency				, // = 1 << 89,
		JewelryStore				, // = 1 << 90,
		Laundry						, // = 1 << 91,
		Lawyer						, // = 1 << 92,
		Library						, // = 1 << 93,
		LiquorStore					, // = 1 << 94,
		LocalGovernmentOffice		, // = 1 << 96,
		Locksmith					, // = 1 << 97,
		Lodging						, // = 1 << 98,
		MealDelivery				, // = 1 << 99,
		MealTakeaway				, // = 1 << 100,
		Mosque						, // = 1 << 101,
		MovieRental					, // = 1 << 102,
		MovieTheater				, // = 1 << 103,
		MovingCompany				, // = 1 << 104,
		Museum						, // = 1 << 105,
		NightClub					, // = 1 << 106,
		Painter						, // = 1 << 107,
		PetStore					, // = 1 << 108,
		Pharmacy					, // = 1 << 109,
		Physiotherapist				, // = 1 << 110,
		PlaceOfWorship				, // = 1 << 111,
		Plumber						, // = 1 << 112,
		Police						, // = 1 << 113,
		PostOffice					, // = 1 << 114,
		RealEstateAgency			, // = 1 << 115,
		Restaurant					, // = 1 << 116,
		RoofingContractor			, // = 1 << 117,
		RvPark						, // = 1 << 118,
		School						, // = 1 << 119,
		ShoeStore					, // = 1 << 120,
		ShoppingMall				, // = 1 << 121,
		Spa							, // = 1 << 122,
		Stadium						, // = 1 << 123,
		Storage						, // = 1 << 124,
		Store						, // = 1 << 125,
		SubwayStation				, // = 1 << 126,
		Synagogue					, // = 1 << 128,
		TaxiStand					, // = 1 << 129,
		TravelAgency				, // = 1 << 130,
		University					, // = 1 << 131,
		VeterinaryCare				, // = 1 << 132,
		Zoo							, // = 1 << 133
	}
}