// ***********************************************************************
// Assembly         : Invisionware.Net.GeoCoding.Interfaces
// Author           : shawn.anderson
// Created          : 06-27-2015
//
// Last Modified By : shawn.anderson
// Last Modified On : 06-28-2015
// ***********************************************************************
// <copyright file="AddressTypes.cs" company="Invisionware">
//     Copyright ©  2015
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Invisionware.Net.GeoCoding
{
	/// <summary>
	/// Enum AddressTypes
	/// </summary>
	public enum AddressTypes
	{
		StreetAddress,
		Route,
		Intersection,
		Political,
		Country,
		AdministrativeAreaLevel1,
		AdministrativeAreaLevel2,
		AdministrativeAreaLevel3,
		AdministrativeAreaLevel4,
		AdministrativeAreaLevel5,
		ColloquialArea,
		Locality,
		Ward,
		Sublocality,
		Neighborhood,
		Premise,
		Subpremise,
		PostalCode,
		NaturalFeature,
		Airport,
		Park,
		PointOfInterest,
		Floor,
		Establishment,
		Parking,
		PostBox,
		PostalTown,
		Room,
		StreetNumber,
		BusStation,
		TrainStation,
		TransitStation,
		Geocode,
		PostalCodePrefix,
		PostalCodeSuffix,
		SublocalityLevel5,
		SublocalityLevel4,
		SublocalityLevel3,
		SublocalityLevel2,
		SublocalityLevel1,
		Accounting,
		AmusementPark,
		Aquarium,
		ArtGallery,
		Atm,
		Bakery,
		Bank,
		Bar,
		BeautySalon,
		BicycleStore,
		BookStore,
		BowlingAlley,
		Cafe,
		Campground,
		CarDealer,
		CarRental,
		CarRepair,
		CarWash,
		Casino,
		Cemetery,
		Church,
		CityHall,
		ClothingStore,
		ConvenienceStore,
		Courthouse,
		Dentist,
		DepartmentStore,
		Doctor,
		Electrician,
		ElectronicsStore,
		Embassy,
		Finance,
		FireStation,
		Florist,
		Food,
		FuneralHome,
		FurnitureStore,
		GasStation,
		GeneralContractor,
		GroceryOrSupermarket,
		Gym,
		HairCare,
		HardwareStore,
		Health,
		HinduTemple,
		HomeGoodsStore,
		Hospital,
		InsuranceAgency,
		JewelryStore,
		Laundry,
		Lawyer,
		Library,
		LiquorStore,
		LocalGovernmentOffice,
		Locksmith,
		Lodging,
		MealDelivery,
		MealTakeaway,
		Mosque,
		MovieRental,
		MovieTheater,
		MovingCompany,
		Museum,
		NightClub,
		Painter,
		PetStore,
		Pharmacy,
		Physiotherapist,
		PlaceOfWorship,
		Plumber,
		Police,
		PostOffice,
		RealEstateAgency,
		Restaurant,
		RoofingContractor,
		RvPark,
		School,
		ShoeStore,
		ShoppingMall,
		Spa,
		Stadium,
		Storage,
		Store,
		SubwayStation,
		Synagogue,
		TaxiStand,
		TravelAgency,
		University,
		VeterinaryCare,
		Zoo
	}
}